### ISSUE TITLE
Error drive MYSQL

### ISSUE THREAD

**Issue by HidenNetworKNET** [NathanCollaert/AugmentedHardcore#40]
Helpme please.

[17:20:13 ERROR] [Minecraft]: Error occurred while enabling AugmentedHardcore v3.3.7 (Is it up to date?)
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://dolly.hiden-ns.com:3306/s38_AugmentedHardcore
        at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:326) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:112) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:93) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[?:?]
        at com.backtobedrock.augmentedhardcore.AugmentedHardcore.initDB(AugmentedHardcore.java:195) ~[?:?]
        at com.backtobedrock.augmentedhardcore.AugmentedHardcore.initialize(AugmentedHardcore.java:162) ~[?:?]
        at com.backtobedrock.augmentedhardcore.AugmentedHardcore.onEnable(AugmentedHardcore.java:60) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:264) ~[arclight-1.18.2-1.0.8-SNAPSHOT-3014a12e.jar%2369!/:arclight-1.18.2-1.0.8-SNAPSHOT-3014a12e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.18.2-1.0.8-SNAPSHOT-3014a12e.jar%2369!/:arclight-1.18.2-1.0.8-SNAPSHOT-3014a12e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.18.2-1.0.8-SNAPSHOT-3014a12e.jar%2369!/:arclight-1.18.2-1.0.8-SNAPSHOT-3014a12e]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServerMixin.java:518) ~[arclight-1.18.2-1.0.8-SNAPSHOT-3014a12e.jar%2369!/:arclight-1.18.2-1.0.8-SNAPSHOT-3014a12e]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServerMixin.java:432) ~[arclight-1.18.2-1.0.8-SNAPSHOT-3014a12e.jar%2369!/:arclight-1.18.2-1.0.8-SNAPSHOT-3014a12e]
        at net.minecraft.server.MinecraftServer.handler$zha000$arclight$enablePlugins(MinecraftServerMixin.java:2217) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:403) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:316) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:173) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2099) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.sql.SQLException: No suitable driver
        at java.sql.DriverManager.getDriver(DriverManager.java:299) ~[java.sql:?]
        at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106) ~[?:?]
        ... 19 more

**Comment by NathanCollaert** [comment]
Are you sure you are using the correct database credentials? If so, what type of database are you using?
